version: '2'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
     - .env
    volumes:
      - ./app/:/app/
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
