services:
  scraper-api:
    image: scraper-api:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
     - .env
  web-app:
    build: ./flask-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - scraper-api
    volumes:
      - ./flask-app/:/app/
    env_file:
     - .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
