services:
  web-app:
    build: ./web-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - scraper-api
    volumes:
      - ./web-app/:/app/
    env_file:
     - .env
  bc-api:
    build: ./bigcommerce-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./bigcommerce-api/:/app/
    env_file:
     - .env
  scraper-api:
    build: ./scraper-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./scraper-api/:/app/
    env_file:
     - .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
